#!/bin/sh
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
export QT_DBL_CLICK_DIST=150
if [ -f /data/params/d/dp_nav ]; then
  NAV=`cat /data/params/d/dp_nav`
else
  NAV="0"
fi

if [ $NAV == "0" ] && [ -f /data/openpilot/selfdrive/ui/_ui_nonav ]; then
  exec ./_ui_nonav
else
  exec ./_ui
fi
