#!/bin/sh
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
export QT_DBL_CLICK_DIST=150
NAV=`cat /data/params/d/dp_nav`
if [ -f /data/params/d/dp_nav ] && [ $NAV != "0" ]; then
  exec ./_ui
else
  exec ./_ui_nonav
fi
